### ISSUE TITLE
连续查询几次后似乎会触发登录页面

### ISSUE THREAD

**Issue by vivagonna** [fugary/simple-boot-douban-api#1]
```2021-08-24 15:49:31,stdout,	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]

2021-08-24 15:49:31,stdout,	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]

2021-08-24 15:49:31,stdout,	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]

2021-08-24 15:49:31,stdout,	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) ~[tomcat-embed-core-9.0.50.jar!/:na]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]

2021-08-24 15:49:31,stdout,	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]

2021-08-24 15:49:31,stdout,	at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[na:na]

2021-08-24 15:49:31,stdout,	at com.fugary.simple.douban.controller.DoubanApiController.searchBook(DoubanApiController.java:73) ~[classes!/:0.0.1-SNAPSHOT]

2021-08-24 15:49:31,stdout,	at com.fugary.simple.douban.controller.DoubanApiController.searchBookElementsNew(DoubanApiController.java:120) ~[classes!/:0.0.1-SNAPSHOT]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:819) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:109) ~[spring-web-5.3.9.jar!/:5.3.9]

2021-08-24 15:49:31,stdout,    <style... (1210 bytes)]

2021-08-24 15:49:31,stdout,    <title>豆瓣 - 登录跳转页</title>

2021-08-24 15:49:31,stdout,"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
"
2021-08-24 15:49:31,stdout,    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

2021-08-24 15:49:31,stdout,<head>

2021-08-24 15:49:31,stdout,org.springframework.web.client.HttpClientErrorException$Forbidden: 403 Forbidden: [<html>
```

**Comment by fugary** [comment]
Douban有自己的防御机制，高频率访问时是会跳转登陆页，新版增加了缓存，重复查询的时候可以减少Douban访问，降低被拦的风险
